### ISSUE TITLE
Error loading module in Chromium

### ISSUE THREAD

**Issue by dodoshanti** [flauc/angular2-notifications#108]
We are having trouble getting the component to load within Chromium/41.0.2272. It loads fine within latest Chrome. This used to work on the same the above Chromium build before but we now get this error:
Unexpected reserved word
	SyntaxError: Unexpected reserved word
	    at eval (native)
	    at Object.eval (http://localhost:5555/node_modules/angular2-notifications/components.js:2:37)
	    at eval (http://localhost:5555/node_modules/angular2-notifications/components.js:17:4)
	    at eval (http://localhost:5555/node_modules/angular2-notifications/components.js:18:3)
	Evaluating http://localhost:5555/node_modules/angular2-notifications/src/simple-notifications.module.js
	Evaluating http://localhost:5555/node_modules/angular2-notifications/components.js
	Evaluating http://localhost:5555/app/app.module.js

The systemjs config and import is per the example. We don't use any shared NgModule, just the root AppModule

**Comment by flauc** [comment]
Thanks for pointing this out I'll have a look 👍

**Comment by flauc** [comment]
I'm having a hard time understanding this. This is the only code in the components.js file: 

```js
"use strict";
var simple_notifications_module_1 = require('./src/simple-notifications.module');
exports.SimpleNotificationsModule = simple_notifications_module_1.SimpleNotificationsModule;
var simple_notifications_component_1 = require('./src/simple-notifications.component');
exports.SimpleNotificationsComponent = simple_notifications_component_1.SimpleNotificationsComponent;
var notification_component_1 = require('./src/notification.component');
exports.NotificationComponent = notification_component_1.NotificationComponent;
var notifications_service_1 = require('./src/notifications.service');
exports.NotificationsService = notifications_service_1.NotificationsService;
var max_pipe_1 = require('./src/max.pipe');
exports.MaxPipe = max_pipe_1.MaxPipe;
var push_notifications_module_1 = require('./src/push-notifications.module');
exports.PushNotificationsModule = push_notifications_module_1.PushNotificationsModule;
var push_notifications_service_1 = require('./src/push-notifications.service');
exports.PushNotificationsService = push_notifications_service_1.PushNotificationsService;
//# sourceMappingURL=components.js.map
```

What could be cousin the issue in that

**Comment by dodoshanti** [comment]
Exactly,  I couldn't see anything wrong with it. 

We've been using the library since Angular 2 beta days and had no issues. I have no problem importing the NotificationService directly within the AppModule.

You can recreate it with the basic example running on this client(cefclient mac or win) here:
[https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_6.x](url)


Thanks for looking at this.
