### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by zbitname** [flauc/angular2-notifications#115]
```
Error: Error at C:/user/app/aot/node_modules/angular2-notifications/src/notification.component.ngfactory.ts:518:69: Property '$e' does not exist on type 'NotificationComponent'.
    at check (C:\user\app\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (C:\user\app\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at C:\user\app\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
Compilation failed
```
What am I doing wrong?

**Comment by michalstepien** [comment]
Yep it is bug.
In notification.component.ts in template should be (click)="onClick($event)" not (click)="onClick($e)"

**Comment by zbitname** [comment]
@michalstepien, thank you! It's help for me :)

**Comment by zbitname** [comment]
The problem is solved
