### ISSUE TITLE
ctorParameters.map is not a function

### ISSUE THREAD

**Issue by Kyaw-Htet** [flauc/angular2-notifications#128]
Hi there, 

I am getting this error, I've got the mappings in systejsconfig file, have imported the SimpleNotificationsModule into my AppModule.   

(SystemJS) ctorParameters.map is not a function
	TypeError: ctorParameters.map is not a function
	    at ReflectionCapabilities.parameters (http://localhost:65302/node_modules/@angular/core/bundles/core.umd.js:1780:49)
	    at Reflector.parameters (http://localhost:65302/node_modules/@angular/core/bundles/core.umd.js:1922:48)
	    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:65302/node_modules/@angular/compiler/bundles/compiler.umd.js:14534:56)
	    at CompileMetadataResolver.getTypeMetadata (http://localhost:65302/node_modules/@angular/compiler/bundles/compiler.umd.js:14499:28)
	    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:65302/node_modules/@angular/compiler/bundles/compiler.umd.js:14274:30)
	    at eval (http://localhost:65302/node_modules/@angular/compiler/bundles/compiler.umd.js:14343:51)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:65302/node_modules/@angular/compiler/bundles/compiler.umd.js:14336:46)
	    at eval (http://localhost:65302/node_modules/@angular/compiler/bundles/compiler.umd.js:14324:52)

**Comment by thanhtran621992** [comment]
Hi, Please upgrade angular core.

**Comment by Kyaw-Htet** [comment]
Thank you very much. I got it. and special thanks to super fast reply.
