### ISSUE TITLE
Error with ng-xi18n command

### ISSUE THREAD

**Issue by ghidoz** [flauc/angular2-notifications#129]
Hi,

I have a problem with the [Angular i18n](https://angular.io/docs/ts/latest/cookbook/i18n.html).
When I run the `ng-xi18n` command, in order to get the texts to translate from my application and generate a xmb file, I get this error:

```
Error: ENOENT: no such file or directory, open '/path/to/my/app/dist/out-tsc/node_modules/angular2-notifications/src/push-notifications.service.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at MetadataWriterHost.writeMetadata (/path/to/my/app/node_modules/@angular/tsc-wrapped/src/compiler_host.js:156:22)
    at MetadataWriterHost.writeFile (/path/to/my/app/node_modules/@angular/tsc-wrapped/src/compiler_host.js:143:19)
    at Object.writeFile (/path/to/my/app/node_modules/typescript/lib/typescript.js:45369:132)
    at Object.writeFile (/path/to/my/app/node_modules/typescript/lib/typescript.js:7602:14)
    at writeEmittedFiles (/path/to/my/app/node_modules/typescript/lib/typescript.js:37859:20)
    at doEmit (/path/to/my/app/node_modules/typescript/lib/typescript.js:37719:17)
    at emitFile /path/to/my/app/node_modules/typescript/lib/typescript.js:44665:21)
Extraction failed
```

I have no other issue in my app: building the app, even with AOT, it's working.

My environment:
```
angular2-notifications: 0.4.49
angular-cli: 1.0.0-beta.24
node: 4.5.0
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/platform-server: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1
```

Any suggestion?

**Comment by flauc** [comment]
Hey @ghidoz 

huh, I'm sorry man I haven't tried using the translate feature yet. I'll try looking in to this over the weekend, sorry I can't do it earlier.

**Comment by flauc** [comment]
Let me know if you dig something up by then.

**Comment by ghidoz** [comment]
Thanks man!

**Comment by zbitname** [comment]
I have some problem
```
Error: ENOENT: no such file or directory, open 'C:\user\project\client\dist\out-tsc\node_modules\angular2-notifications\src\icons.metadata.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.writeFileSync (fs.js:1223:33)
    at MetadataWriterHost.writeMetadata (C:\user\project\client\node_modules\@angular\tsc-wrapped\src\compiler_host.js:164:22)
    at MetadataWriterHost.writeFile (C:\user\project\client\node_modules\@angular\tsc-wrapped\src\compiler_host.js:143:19)
    at Object.writeFile (C:\user\project\client\node_modules\typescript\lib\typescript.js:62935:132)
    at Object.writeFile (C:\user\project\client\node_modules\typescript\lib\typescript.js:8930:14)
    at printFile (C:\user\project\client\node_modules\typescript\lib\typescript.js:60024:16)
    at emitFile (C:\user\project\client\node_modules\typescript\lib\typescript.js:59973:21)
    at onSingleFileEmit (C:\user\project\client\node_modules\typescript\lib\typescript.js:8838:13)
    at Object.forEachTransformedEmitFile (C:\user\project\client\node_modules\typescript\lib\typescript.js:8815:21)
Extraction failed
```
What i do wrong?

**Comment by martinop** [comment]
I have this problem too:
Error: ENOENT: no such file or directory, open 'C:\Users\marti\Documents\Dev\uriji-jami-web-app\dist\node_modules\angular2-notifications\src\icons.metadata.json'
