### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by davidbarratt** [flauc/angular2-notifications#206]
This library appears to use ES6 modules which Node.js does not support.

```
node_modules/angular2-notifications/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './src/push-notifications.module';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.cls_wrapMethod [as _load] (node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (dist/compiled/client/app/brand.service.js:6:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.cls_wrapMethod [as _load] (node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (dist/compiled/server/index.js:10:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.cls_wrapMethod [as _load] (node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (index.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

Would it be possible to support Node.js by _not_ using ES6 modules in `dist` ?

**Comment by xealot** [comment]
Right now the recommendation for Angular libraries is to provide both.

```
├── package.json 
|      typings: ./core.d.ts
|         main: ./bundles/core.umd.js
|       module: ./@angular/core.es5.js
|       es2015: ./@angular/core.js
```

[Angular Packaging Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#)

**Comment by AnthonyNahas** [comment]
take a look of my solution [here](https://github.com/SebastianM/angular-google-maps/issues/1052)

**Comment by flauc** [comment]
This error should be resolved with the latest release as well. Please reopen if you are still seeing it though.
