### ISSUE TITLE
No provider for t!

### ISSUE THREAD

**Issue by limpep** [flauc/angular2-notifications#215]
Hi, 

Using the latest version, but when I build to prod using AOT i get the following error 

```
Unhandled Promise rejection: No provider for t! ; Zone: angular ; Task: Promise.then ; Value: Error: No provider for t!
    at x (vendor.20cb9d4….bundle.js:10)
    at k (vendor.20cb9d4….bundle.js:10)
    at t._throwOrNull (vendor.20cb9d4….bundle.js:25)
    at t._getByKeyDefault (vendor.20cb9d4….bundle.js:25)
    at t._getByKey (vendor.20cb9d4….bundle.js:25)
    at t.get (vendor.20cb9d4….bundle.js:25)
    at n.t.get (vendor.20cb9d4….bundle.js:25)
    at pn (vendor.20cb9d4….bundle.js:19)
    at cn (vendor.20cb9d4….bundle.js:19)
    at on (vendor.20cb9d4….bundle.js:19) Error: No provider for t!
    at x (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:10:275)
    at k (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:10:534)
    at t._throwOrNull (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:25:22223)
    at t._getByKeyDefault (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:25:22556)
    at t._getByKey (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:25:21941)
    at t.get (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:25:20349)
    at n.t.get (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:25:27866)
    at pn (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:19:5908)
    at cn (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:19:4750)
    at on (http://localhost/vendor.20cb9d4a563c5eb31e10.bundle.js:19:3005)
```

I am using node 8.0.0 and npm 5.0.1 with Angular cli, 

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.0
node: 8.0.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6-52b6692
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
```

**Comment by MrFranke** [comment]
+1
I have that error with lazy load module and AOT:
```
 No provider for NotificationsService!
```

**Comment by MrFranke** [comment]
@limpep i fix this:
Change import from 
`import { NotificationsService } from 'angular2-notifications/dist';`
to 
`import { NotificationsService } from 'angular2-notifications';`

Hope it's help.

**Comment by limpep** [comment]
@MrFranke Nice thanks, I'll give it a shot.

**Comment by limpep** [comment]
@MrFranke Just tested it on my project and it is working, thanks!

**Comment by FunClub** [comment]
Nice thanks,
