### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by sunnyke** [flauc/angular2-notifications#252]
1.Error:
Module build failed: TypeError: Cannot read property 'content' of undefined

2.  Log:
$ ionic cordova build --prod browser
[INFO] Running app-scripts build: --prod --platform browser --target cordova

[10:22:05]  build prod started ...
[10:22:05]  clean started ...
[10:22:05]  clean finished in 49 ms
[10:22:05]  copy started ...
copy config for environment : undefined
platform is  undefined
[ './update.json' ]
[10:22:05]  ngc started ...
[10:22:33]  ngc finished in 27.68 s
[10:22:33]  preprocess started ...
[10:22:33]  deeplinks started ...
[10:22:34]  deeplinks finished in 977 ms
[10:22:34]  optimization started ...
[10:22:35]  copy finished in 30.11 s
Error: ./~/angular2-notifications/src/simple-notifications.module.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 276:0-84
 @ ./src/app/main.ts,./~/angular2-notifications/src/simple-notifications/services/notifications.service.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 282:0-108
 @ ./src/app/main.ts,./~/angular2-notifications/src/simple-notifications/components/simple-notifications.component.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./~/p-wit-notification/src/notification.component.ngfactory.js 11:0-117
 @ ./src/pages/app-tabs/app-tabs-pc/app-tabs-pc.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./~/angular2-notifications/src/simple-notifications/components/notification.component.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./~/angular2-notifications/src/simple-notifications/components/simple-notifications.component.ngfactory.js 9:0-109
 @ ./~/p-wit-notification/src/notification.component.ngfactory.js
 @ ./src/pages/app-tabs/app-tabs-pc/app-tabs-pc.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./~/angular2-notifications/src/simple-notifications/pipes
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (D:\sunny\project\review-test\wow_webgui\node
    at Object.loader (D:\sunny\project\review-test\wow_webgui\node_modules\@io
 @ ./~/angular2-notifications/src/simple-notifications/components/notification
 @ ./~/angular2-notifications/src/simple-notifications/components/simple-notif
 @ ./~/p-wit-notification/src/notification.component.ngfactory.js
 @ ./src/pages/app-tabs/app-tabs-pc/app-tabs-pc.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (D:\sunny\project\review-test\wow_webgui\node_modules\@i
    at D:\sunny\project\review-test\wow_webgui\node_modules\@ionic\app-scripts
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by sunnyke** [comment]
v0.7.8, don't support ngc aot?

**Comment by sunnyke** [comment]
Reason:
project use node_modules/angular2-notifications/src, not node_modules/angular2-notifications/dist,
In fact, should release angular2-notifications just contain dist folder content, others should remove, then run ok.

**Comment by sunnyke** [comment]
The package.json main=./dist/index.js not work in ngc mode, can you help me, tks.

**Comment by flauc** [comment]
Hi @sunnyke, sorry for the long wait. Should be resolved with the latest release. Let me know if you're still seeing it though.
