### ISSUE TITLE
'SimpleNotificationsModule' is not exported by node_modules/angular2-notifications/dist/index.js

### ISSUE THREAD

**Issue by QDebesson** [flauc/angular2-notifications#257]
Hey!

I've been using this lib for a while and it was great! 
I'm currently trying to use it inside a component lib but I'm facing some issues:

```
import { SimpleNotificationsModule } from 'angular2-notifications';

@NgModule({
  imports: [
    SimpleNotificationsModule.forRoot()
  ],
  declarations: [],
  exports: [],
  providers: [
    ToasterService
  ]
})
export class ServicesModule {
}
```

gives me this error when lib-building:

```
BUILD ERROR
'SimpleNotificationsModule' is not exported by node_modules/angular2-notifications/dist/index.js
Error: 'SimpleNotificationsModule' is not exported by node_modules/angular2-notifications/dist/index.js
    at error (/home/myproject/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (/home/myproject/node_modules/rollup/dist/rollup.js:8390:3)
    at Module.trace (/home/myproject/node_modules/rollup/dist/rollup.js:8487:10)
    at ModuleScope.findVariable (/home/myproject/node_modules/rollup/dist/rollup.js:8093:22)
    at Node.bind (/home/myproject/node_modules/rollup/dist/rollup.js:7339:30)
    at eachChild.child (/home/myproject/node_modules/rollup/dist/rollup.js:5819:34)
    at keys.forEach.key (/home/myproject/node_modules/rollup/dist/rollup.js:5847:5)
    at Array.forEach (native)
    at Node.eachChild (/home/myproject/node_modules/rollup/dist/rollup.js:5840:13)
    at Node.bind (/home/myproject/node_modules/rollup/dist/rollup.js:5819:8)
```
but a classic `ng build` works fine.
If I change the route to `import { SimpleNotificationsModule } from 'angular2-notifications/dist/src/simple-notifications.module';` it builds but I have this error on the consuming app:

`Error: Error encountered resolving symbol values statically. Calling function 'SimpleNotificationsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol ServicesModule in /home/myapp/node_modules/myproject/myproject.d.ts, resolving symbol ServicesModule in /home/myapp/node_modules/myproject/myproject.d.ts`

Is this an issue on your side or am I doing something wrong?

Thanks!

-- "angular2-notifications": "^0.7.7"

**Comment by flauc** [comment]
I think this should be resolved in the latest version. Please reopen the issue if you are still seeing this problem. Also, if you are still getting it please try to provide a minimal plunkr for it.
